### ISSUE TITLE
Temporary file management on shared filesystems

### ISSUE THREAD

**Issue by johnwarburton** [dadav/gorge#19]
Hi @dadav 

We are running our internal puppet gorge server as 3 Kubernetes pods all mounting the **same** `modulesdir` via NFS

On a semi regular basis (no real pattern - today was 1h, 1.5h, 6h before), one of the 3 the gorge server pods will restart with something like this in the logs:
```
 running /usr/local/bin/gorge serve --ui  --bind 0.0.0.0 --port 8080     --modulesdir /gorge/modules --cache-max-age=86400     --modules-scan-sec 60
 {"level":"info","ts":1722168865.5311682,"caller":"cmd/serve.go:246","msg":"Listen on 0.0.0.0:8080"}
 {"level":"panic","ts":1722168925.8064713,"caller":"cmd/serve.go:301","msg":"EOF","stacktrace":"github.com/dadav/gorge/cmd.init.func2\n\t/go/pkg/mod/github.com/dadav/gorge
@v0.0.0-20240723175256-1a46936356fd/cmd/serve.go:301\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf1
3/cobra@v1.8.0/command.go:1115\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039\ngithub.com/dadav/gorge/cmd.Execute\n\t/go/pkg/mod/github.com/dadav/gorge@v0.0.0-20240723175256
-1a46936356fd/cmd/root.go:49\nmain.main\n\t/go/pkg/mod/github.com/dadav/gorge@v0.0.0-20240723175256-1a46936356fd/main.go:21\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:271"}
 panic: EOF

 goroutine 1 [running]:
 go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x0?, 0x0?, {0x0?, 0x0?, 0xc000132080?})
     /go/pkg/mod/go.uber.org/zap@v1.27.0/zapcore/entry.go:196 +0x54
 go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00012e1a0, {0x0, 0x0, 0x0})
     /go/pkg/mod/go.uber.org/zap@v1.27.0/zapcore/entry.go:262 +0x24e
 go.uber.org/zap.(*SugaredLogger).log(0xc0000b2190, 0x4, {0x0?, 0xc00016d780?}, {0xc00016dc68?, 0xb75f60?, 0xee0690?}, {0x0, 0x0, 0x0})
     /go/pkg/mod/go.uber.org/zap@v1.27.0/sugar.go:355 +0xec
 go.uber.org/zap.(*SugaredLogger).Panic(0xc000126000?, {0xc00016dc68?, 0xc00012c020?, 0xc00010fc68?})
     /go/pkg/mod/go.uber.org/zap@v1.27.0/sugar.go:180 +0x38                                                                                                                 github.com/dadav/gorge/cmd.init.func2(0xc0001c8200?, {0xa00e9c?, 0x4?, 0xa00ea0?})                                                                                             /go/pkg/mod/github.com/dadav/gorge@v0.0.0-20240723175256-1a46936356fd/cmd/serve.go:301 +0x1a45                                                                         github.com/spf13/cobra.(*Command).execute(0xef0160, {0xc0001d9180, 0xa, 0xa})                                                                                                  /go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xab1                                                                                                        github.com/spf13/cobra.(*Command).ExecuteC(0xeefe80)                                                                                                                           /go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff                                                                                                       github.com/spf13/cobra.(*Command).Execute(...)                                                                                                                                 /go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039                                                                                                              github.com/dadav/gorge/cmd.Execute()                                                                                                                                           /go/pkg/mod/github.com/dadav/gorge@v0.0.0-20240723175256-1a46936356fd/cmd/root.go:49 +0x1a                                                                             main.main()                                                                                                                                                                    /go/pkg/mod/github.com/dadav/gorge@v0.0.0-20240723175256-1a46936356fd/main.go:21 +0xf
```
Other messages I have seen (apart from ` panic: EOF` above) are:
```
panic: gzip: invalid header
panic: unexpected EOF
```
I initially thought the code that read in the files as gzipped tar balls was unpacking the files (`gunzip`/`tar xf` equivalents) but I can see in the code, it is all reading into buffers. 

The only other time I have seen something like this happen in the past when the expected forge tar ball created by `pdk build` was zero length

The only place I can directly see temporary files being created in the `os.CreateTemp` call in `pkg/gen/v3/openapi/routers.go`. I was wondering if a temporary file being written here and then being read from another pod as a forge module (in`internal/v3/backend/filesystem.go`) might be the cause of the errors?

Any pointers to help debugging this would be appreciated as I can't quite see where these functions are being called

Thanks
John

**Comment by dadav** [comment]
Hi @johnwarburton,

thank you - as always - for your awesome issues. I'm on it.
